sender-email: "sendertpsi@gmail.com"
report-file-folder-path: "/app/shared/"
server:
  servlet:
    context-path: /api
  port: 8084
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/finalproject
    username: postgres
    password: post123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: mailinfo
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: mailinfo
  mail:
    host: smtp.gmail.com
    port: 465
    username: "sendertpsi@gmail.com"
    password: "zhznulbwawdvbrwm"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        springframework: INFO
queue:
  export: export-salaries-queue
  export-filtered: export-filtered-salaries-queue
