package com.finalproject.portal.enums;

public enum ErrorResponseCode {

    COLLABORATOR_NOT_FOUND,
    ADDRESS_NOT_FOUND,
    USER_ALREADY_EXISTS,
    NIF_ALREADY_EXISTS,
    BAD_CREDENTIALS,
    TOKEN_STILL_VALID,
    REFRESH_TOKEN_INVALID,
    USER_CREDENTIALS_NOT_FOUND,
    COMPONENT_TYPE_NOT_FOUND,
    COMPONENT_TYPE_SUBTYPE_NOT_FOUND,
    SALARY_COMPONENT_NOT_FOUND,
    SALARY_NOT_FOUND,
    SALARY_IS_ALREADY_APPROVED,
    SALARY_IS_ALREADY_ACTIVE,
    SALARY_CANNOT_BE_APPROVED_ANYMORE,
    SALARY_CANNOT_BE_UPDATED_ANYMORE,
    DUPLICATED_SALARY_FOR_IMPLEMENTATION_DATE,
    ROLE_NOT_FOUND,
    OPTIMISTIC_LOCKING_FAILURE
}
