services:
  rabbitmq:
    image: rabbitmq:4.0.3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: finalproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql

  authentication:
    build: ./authentication/authentication
    container_name: authentication-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finalproject
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: post123
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  collaborator-information:
    build: ./collaborator/collaborator
    container_name: collaborator-information-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finalproject
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: post123
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  salary-management:
    build: ./salarymanagement/salarymanagement
    container_name: salary-management-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finalproject
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: post123
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    ports:
      - "8083:8083"
    volumes:
      - shared-files:/app/shared
    depends_on:
      - postgres
      - rabbitmq

  mail-gateway:
    build: ./mail-gateway/mail-gateway
    container_name: mail-gateway-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finalproject
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: post123
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    ports:
      - "8084:8084"
    volumes:
      - shared-files:/app/shared
    depends_on:
      - postgres
      - rabbitmq

  portal:
    build: ./portal/portal
    container_name: portal-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finalproject
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: post123
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - authentication
      - collaborator-information
      - salary-management
      - mail-gateway

volumes:
  postgres_data:
  shared-files:
