package com.finalproject.salarymanagement.enums;

public enum ErrorResponseCode {

    COMPONENT_TYPE_NOT_FOUND,
    COMPONENT_TYPE_SUBTYPE_NOT_FOUND,
    SALARY_COMPONENT_NOT_FOUND,
    SALARY_NOT_FOUND,
    SALARY_IS_ALREADY_APPROVED,
    SALARY_IS_ALREADY_ACTIVE,
    SALARY_CANNOT_BE_APPROVED_ANYMORE,
    SALARY_CANNOT_BE_UPDATED_ANYMORE,
    DUPLICATED_SALARY_FOR_IMPLEMENTATION_DATE,

}
